
spring.application.name=movie-recsys-backend
server.port=8081

# Spring Datasource Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/movie_recsys
spring.datasource.username=root
spring.datasource.password=Stark@1945
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# logging configuration
logging.level.root=INFO
logging.level.com.movie.recsys=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG
